[tool.poetry]
name = "propra-webscience-ws24"
version = "0.1.0"
description = "Web Science - Sentiment Analysis Twitter"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.8"
datasets = "^3.2.0"
evaluate = "^0.4.3"
humanize = "^4.11.0"
jupyter = "^1.1.1"
loguru = "^0.7.3"
matplotlib = "^3.9.2"
nltk = "^3.9.1"
ollama = "^0.4.7"
pandas = "^2.2.3"
pyarrow = "^18.0.0"
scikit-learn = "^1.5.2"
seaborn = "^0.13.2"
torch = "^2.5.1"
transformers = {extras = ["torch"], version = "^4.47.0"}


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
mypy = "^1.12.1"
pre-commit = "^4.0.1"
ruff = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
