create_pdf: abschlussbericht-stimmungsanalyse-mit-twitter.tex references.bib
	pdflatex abschlussbericht-stimmungsanalyse-mit-twitter.tex
	bibtex abschlussbericht-stimmungsanalyse-mit-twitter
	pdflatex abschlussbericht-stimmungsanalyse-mit-twitter.tex
	pdflatex abschlussbericht-stimmungsanalyse-mit-twitter.tex

clean:
	rm -f *.aux *.bbl *.blg *.log *.out *.toc *.glo *.gls *.glsdefs *.ist *.glg

.PHONY: clean
